config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'homes#index'

  resources :posts do
    scope module: :posts do
      resources :comments
      resources :likes
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :posts, dependent: :restrict_with_exception

  validates :name, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :category
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id', inverse_of: :posts

  has_many :comments, class_name: 'PostComment', dependent: :destroy
  has_many :likes, class_name: 'PostLike', dependent: :destroy

  validates :body, presence: true
  validates :title, presence: true

  def like_by_user(user)
    likes.find_by(user:)
  end
end

app/models/post_comment.rb
# frozen_string_literal: true

class PostComment < ApplicationRecord
  has_ancestry

  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/post_like.rb
# frozen_string_literal: true

class PostLike < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :restrict_with_exception
  has_many :post_comments, dependent: :restrict_with_exception
  has_many :likes, class_name: 'PostLike', dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/homes_controller.rb
# frozen_string_literal: true

class HomesController < ApplicationController
  def index
    @posts = Post.order(created_at: :desc)
  end
end

app/controllers/posts/application_controller.rb
# frozen_string_literal: true

module Posts
  class ApplicationController < ApplicationController
  end
end

app/controllers/posts/comments_controller.rb
# frozen_string_literal: true

module Posts
  class CommentsController < ApplicationController
    before_action :set_post, only: %i[index create]
    before_action :authenticate_user!, only: %i[create]

    def index
      @post_comments = @post.comments
    end

    def new
      @post_comment = Comment.new(parent_id: post_comment_params[:parent_id])
    end

    def create
      @post_comment = @post.comments.build(post_comment_params)
      @post_comment.user = current_user

      if @post_comment.save
        redirect_to post_path(@post), notice: t('comments.success_notice')
      else
        redirect_to post_path(@post), status: :unprocessable_entity
      end
    end

    private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def post_comment_params
      params.require(:post_comment).permit(:content, :parent_id)
    end
  end
end

app/controllers/posts/likes_controller.rb
# frozen_string_literal: true

module Posts
  class LikesController < ApplicationController
    before_action :set_post, only: %i[create destroy]
    before_action :find_like, only: %i[destroy]
    before_action :authenticate_user!, only: %i[create destroy]

    def create
      unless already_liked?
        @post_like = @post.likes.build(user_id: current_user.id)

        @post_like.save
      end

      redirect_back_or_to post_path(@post)
    end

    def destroy
      already_liked? && @post_like.destroy

      redirect_back_or_to post_path(@post)
    end

    private

    def set_post
      @post = Post.find(params[:post_id])
    end

    def already_liked?
      PostLike.exists?(user_id: current_user.id, post_id: params[:post_id])
    end

    def find_like
      @post_like = @post.likes.find(params[:id])
    end
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show]
  before_action :authenticate_user!, only: %i[create]

  def index
    @posts = Post.includes(:category, :creator)
  end

  def show
    @comment = PostComment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      redirect_to @post, notice: t('posts.success_notice')
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:body, :title, :category_id)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def new
    super

    @minimum_password_length = User.password_length.min
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      content_tag(:div, render("posts/comments/index", comment: comment), class: "ms-4")
    end.join.html_safe
  end
end

app/helpers/posts/comments_helper.rb
# frozen_string_literal: true

module Posts::CommentsHelper
  def nested_comments(comments)
    comments.map do |comment|
      if comment.has_parent?
        content_tag(:div, render('posts/comments/index', comment: comment), class: 'ms-4')
      else
        render 'posts/comments/index', comment: comment
      end
    end.join
  end
end

app/helpers/posts/likes_helper.rb
# frozen_string_literal: true

module Posts::LikesHelper
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/homes/index.html.slim
= content_for :title do
  = 'Home#index'

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title
      = content_for(:title) || t('title')
    meta[name='viewport' content='width=device-width,initial-scale=1']
    meta[name='apple-mobile-web-app-capable' content='yes']
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    link[rel='icon' href='/icon.png' type='image/png']
    link[rel='icon' href='/icon.svg' type='image/svg+xml']
    link[rel='apple-touch-icon' href='/icon.png']
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module'
  body.d-flex.flex-column
    = render 'layouts/shared/header'

    = render 'layouts/shared/flash'

    = render layout: 'layouts/shared/main' do
      = yield

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container
    - flash.to_hash.each_value do |msg|
      .alert.alert-info
        = msg

app/views/layouts/shared/_header.html.slim
header style="height: 100px;"
  .navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
    .container-fluid
      a.navbar-brand.me-md-4
        img src="/assets/logo.png" width="30"
      ul.navbar-nav.me-auto.mb-2.mb-md-0
        li.nav-item.me-2
          = link_to t('navbar.home'), root_path, class: 'nav-link'
        li.nav-item.me-2
          = link_to t('navbar.posts'), posts_path, class: 'nav-link'
        - unless user_signed_in?
          li.nav-item.me-2
            = link_to t('navbar.sign_in'), new_user_session_path, class: 'nav-link'
          li.nav-item.me-2
            = link_to t('navbar.sign_up'), new_user_registration_path, class: 'nav-link'

      ul.navbar-nav.mb-2.mb-md-0
        - if user_signed_in?
            li.nav-item.me-2
              p.nav-link.disabled.mb-0
                = current_user[:email]
            li.nav-item.me-2
              = link_to t('navbar.new_post'), new_post_path, class: 'nav-link'
            li.nav-item.me-2
              = link_to t('navbar.sign_out'), destroy_user_session_path, class: 'nav-link'

app/views/layouts/shared/_main.html.slim
main.flex-shrink-0
  .container
    = yield

app/views/posts/_form.html.slim
= simple_form_for @post do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    .form-group
      = f.input :body,
        label: t('posts.form.body')
    .form-group
      = f.input :title,
        label: t('posts.form.title'),
        wrapper_html: { class: 'mb-2' }
    .form-group
      = f.association :category,
        label: t('posts.form.category'),
        wrapper_html: { class: 'mb-2' }

  .form-actions
    = f.button :submit, t('posts.form.submit'), class: 'btn btn-outline-success'

app/views/posts/_like.html.slim
- if user_signed_in?
  - pre_like = post.like_by_user current_user

  - if pre_like
    = link_to post_like_path(post, pre_like), id: "like-#{post.id}", class: 'link-dark', \
      data: { turbo_method: :delete }
        i.bi.bi-hand-thumbs-up-fill
  - else
    = link_to post_likes_path(post), id: "like-#{post.id}", class: 'link-dark', \
      data: { turbo_method: :post }
        i.bi.bi-hand-thumbs-up
- else
  i.bi.bi-hand-thumbs-up

app/views/posts/_post.html.slim
.card.mb-3
  .card-body
    h2.h5.card-title
      = link_to post.title, post, class: 'link-dark text-decoration-none'

    = simple_format post.body, { class: 'card-text mb-2' }, wrapper_tag: 'div'

    .d-flex.justify-content-between.mt-5
      .post-section
        span.me-2
          = post.category.name
        '
        span
          = post.creator.email
      .likes-section
        span.me-2 id="count-like-#{post.id}"
          = post.likes_count
          = render 'like', post: post

app/views/posts/comments/_form.html.slim
= simple_form_for(@comment, method: :post, url: post_comments_path(@post)) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-group.text.required.post_comment_content
    = f.input_field :content,
      class: 'form-control'

  .form-group.hidden.post_comment_parent_id
    = f.input_field :parent_id,
      class: 'form-control hidden',
      value: locals[:parent_comment_id],
      type: 'hidden',
      name: 'post_comment[parent_id]',
      id: 'post_comment_parent_id'

  = f.button :submit, t('comments.form.submit'), class: 'btn btn-primary mt-2'

app/views/posts/comments/_index.html.slim
.card.mt-2.rounded-0 id="comment-#{comment.id}"
  .card-header.border-0
    = link_to '#', "#comment-#{comment.id}", class: 'me-2'
    span.me-2
      = @post.creator.email
    span.fs-6.text-muted
      = comment.created_at.to_fs(:short)
  .card-body.border-0
    p.card-text
      = comment.content
  - if user_signed_in?
      .card-footer.border-0
        a.fs-6.text-decoration-underline.text-lowercase{
          role='button'
          data-bs-toggle='collapse'
          aria-expanded='false'
          aria-controls="response_comment-#{comment.id}"
          data-bs-target="#response_comment-#{comment.id}"
          href="#response_comment-#{comment.id}"
        }
          = t('comments.form.reply')
        .collapse.ms-2{
          id="response_comment-#{comment.id}"
        }
          = render 'posts/comments/form', locals: { parent_comment_id: comment.id }

  = sanitize nested_comments(comment.children), attributes: ALLOWED_ATTRIBUTES, tags: ALLOWED_ELEMENTS

app/views/posts/comments/_new.html.slim
== render 'posts/comments/form', locals: {}

app/views/posts/index.html.slim
p style='color: green' = notice

h1
  = t('posts.title')

.row
  .col-md-12
    - @posts.each do |post|
      == render post, post: @post

app/views/posts/new.html.slim
h1
  = t('posts.form.form_title')

== render 'form', post: @post

br

div
  = link_to t('posts.form.back'), posts_path

app/views/posts/show.html.slim
p style='color: green' = notice

== render @post

.lead.mt-3
  span
    = t('posts.show.comments')
    = render 'posts/comments/new'

    = sanitize nested_comments(@post.comments.roots), attributes: ALLOWED_ATTRIBUTES, tags: ALLOWED_ELEMENTS